# TCL File Generated by Component Editor 18.1
# Tue May 12 08:44:36 EDT 2020
# DO NOT MODIFY


# 
# gaa_fitness "GAA fitness" v1.0
#  2020.05.12.08:44:36
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module gaa_fitness
# 
set_module_property DESCRIPTION ""
set_module_property NAME gaa_fitness
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "GAA fitness"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gaa_fitness
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gaa_fitness.sv SYSTEM_VERILOG PATH gaa_fitness.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group gaa
set_module_assignment embeddedsw.dts.name gaa_fitness
set_module_assignment embeddedsw.dts.vendor wgs2113_jcr2198


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point sdram_controller_master
# 
add_interface sdram_controller_master avalon start
set_interface_property sdram_controller_master addressUnits WORDS
set_interface_property sdram_controller_master associatedClock clock
set_interface_property sdram_controller_master associatedReset reset
set_interface_property sdram_controller_master bitsPerSymbol 8
set_interface_property sdram_controller_master burstOnBurstBoundariesOnly false
set_interface_property sdram_controller_master burstcountUnits WORDS
set_interface_property sdram_controller_master doStreamReads false
set_interface_property sdram_controller_master doStreamWrites false
set_interface_property sdram_controller_master holdTime 0
set_interface_property sdram_controller_master linewrapBursts false
set_interface_property sdram_controller_master maximumPendingReadTransactions 0
set_interface_property sdram_controller_master maximumPendingWriteTransactions 0
set_interface_property sdram_controller_master readLatency 0
set_interface_property sdram_controller_master readWaitTime 1
set_interface_property sdram_controller_master setupTime 0
set_interface_property sdram_controller_master timingUnits Cycles
set_interface_property sdram_controller_master writeWaitTime 0
set_interface_property sdram_controller_master ENABLED true
set_interface_property sdram_controller_master EXPORT_OF ""
set_interface_property sdram_controller_master PORT_NAME_MAP ""
set_interface_property sdram_controller_master CMSIS_SVD_VARIABLES ""
set_interface_property sdram_controller_master SVD_ADDRESS_GROUP ""

add_interface_port sdram_controller_master sdram_address address Output 25
add_interface_port sdram_controller_master sdram_byteenable_n byteenable_n Output 2
add_interface_port sdram_controller_master sdram_read_n read_n Output 1
add_interface_port sdram_controller_master sdram_readdata readdata Input 16
add_interface_port sdram_controller_master sdram_readdatavalid readdatavalid Input 1
add_interface_port sdram_controller_master sdram_waitrequest waitrequest Input 1
add_interface_port sdram_controller_master sdram_chipselect chipselect Output 1


# 
# connection point hps_slave
# 
add_interface hps_slave avalon end
set_interface_property hps_slave addressUnits WORDS
set_interface_property hps_slave associatedClock clock
set_interface_property hps_slave associatedReset reset
set_interface_property hps_slave bitsPerSymbol 8
set_interface_property hps_slave burstOnBurstBoundariesOnly false
set_interface_property hps_slave burstcountUnits WORDS
set_interface_property hps_slave explicitAddressSpan 0
set_interface_property hps_slave holdTime 0
set_interface_property hps_slave linewrapBursts false
set_interface_property hps_slave maximumPendingReadTransactions 0
set_interface_property hps_slave maximumPendingWriteTransactions 0
set_interface_property hps_slave readLatency 0
set_interface_property hps_slave readWaitTime 1
set_interface_property hps_slave setupTime 0
set_interface_property hps_slave timingUnits Cycles
set_interface_property hps_slave writeWaitTime 0
set_interface_property hps_slave ENABLED true
set_interface_property hps_slave EXPORT_OF ""
set_interface_property hps_slave PORT_NAME_MAP ""
set_interface_property hps_slave CMSIS_SVD_VARIABLES ""
set_interface_property hps_slave SVD_ADDRESS_GROUP ""

add_interface_port hps_slave hps_chipselect chipselect Input 1
add_interface_port hps_slave hps_write write Input 1
add_interface_port hps_slave hps_readdata readdata Output 8
add_interface_port hps_slave hps_waitrequest waitrequest Output 1
add_interface_port hps_slave hps_read read Input 1
add_interface_port hps_slave hps_writedata writedata Input 8
add_interface_port hps_slave hps_address address Input 2
set_interface_assignment hps_slave embeddedsw.configuration.isFlash 0
set_interface_assignment hps_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment hps_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment hps_slave embeddedsw.configuration.isPrintableDevice 0

